#!/usr/bin/env bash
#
# ID: GFT_ONBOARDING_WORKSPACE_FILES_06
# Title: Onboarding Script - Workspace-Level File Deployment
# Author(s): AI Enablement Lead
# Creation Date: 2026-05-11
# Version: 1.0.0
#
# Description:
#   Deploys versioned workspace-level scripts and docs from the workspace/
#   bundle in this repo to $GFT_PROJECTS_HOME (default: ~/gft_studio).
#   Idempotent: skips files that are already up to date; updates changed ones.

deploy_workspace_files() {
    local target="${GFT_PROJECTS_HOME:-${HOME}/gft_studio}"
    local source_dir="${SCRIPT_DIR}/workspace"

    log_info "Deploying workspace-level files to ${target}..."

    if [[ ! -d "$source_dir" ]]; then
        log_error "Workspace bundle not found at ${source_dir}."
        return 1
    fi

    mkdir -p "$target"

    local deployed=0 updated=0 skipped=0

    while IFS= read -r -d '' src_file; do
        local filename
        filename="$(basename "$src_file")"
        local dest_file="${target}/${filename}"

        if [[ -f "$dest_file" ]] && diff -q "$src_file" "$dest_file" >/dev/null 2>&1; then
            log_info "  ${filename} — up to date."
            skipped=$((skipped + 1))
            continue
        fi

        if [[ -f "$dest_file" ]]; then
            log_info "  ${filename} — updating."
            updated=$((updated + 1))
        else
            log_info "  ${filename} — installing."
            deployed=$((deployed + 1))
        fi

        cp "$src_file" "$dest_file"
        if [[ "$src_file" == *.sh ]]; then
            chmod +x "$dest_file"
        fi
    done < <(find "$source_dir" -maxdepth 1 -type f -print0 | sort -z)

    log_success "Workspace files: ${deployed} installed, ${updated} updated, ${skipped} up to date."
}

deploy_planning_metadata_hook() {
    local target_dir="${GFT_PROJECTS_HOME:-${HOME}/gft_studio}"
    log_info "Deploying central planning metadata pre-commit hook..."

    # Canonical linter script path (resolved relative to the side-by-side repo layout)
    local linter_src="${target_dir}/gcd-ops-scripts/src/gft_ops_scripts/linters/validate_planning_metadata.py"

    # In a testing/mock environment, locate under target_dir as well
    if [[ ! -f "$linter_src" && -d "${target_dir}/linters" ]]; then
        linter_src="${target_dir}/linters/validate_planning_metadata.py"
    fi

    if [[ ! -f "$linter_src" ]]; then
        log_warn "Planning linter script not found at ${linter_src}. Skipping symlink hook deployment."
        return 0
    fi

    # Ensure the script is executable
    chmod +x "$linter_src"

    local deployed=0 skipped=0 failed=0

    # Scan all directories in target_dir to find Git repositories
    for repo_path in "${target_dir}"/*; do
        [[ -e "$repo_path" ]] || continue
        if [[ -d "${repo_path}/.git" ]]; then
            local repo_name
            repo_name=$(basename "$repo_path")
            local hook_dir="${repo_path}/.git/hooks"
            local hook_dest="${hook_dir}/pre-commit"
            local legacy_hook="${hook_dir}/pre-commit.legacy"

            mkdir -p "$hook_dir"

            # Check if this hook dest is already our wrapper and no legacy hook exists
            if [[ -f "$hook_dest" ]]; then
                if grep -q "GenCr@ft Studio - Chained Pre-Commit Hook wrapper" "$hook_dest" 2>/dev/null; then
                    if [[ ! -f "$legacy_hook" ]]; then
                        skipped=$((skipped + 1))
                        continue
                    fi
                fi
            fi

            # Handle existing hooks to enable chaining
            if [[ -f "$hook_dest" && ! -L "$hook_dest" ]]; then
                # If it's already a wrapper, don't move it to legacy!
                if ! grep -q "GenCr@ft Studio - Chained Pre-Commit Hook wrapper" "$hook_dest" 2>/dev/null; then
                    mv "$hook_dest" "$legacy_hook"
                    log_info "  Chained existing pre-commit hook in ${repo_name} to pre-commit.legacy"
                fi
            fi

            # Create the chained wrapper
            cat << EOF > "$hook_dest"
#!/usr/bin/env bash
# GenCr@ft Studio - Chained Pre-Commit Hook wrapper
# Automatically generated by onboarding scripts.

# 1. Run strict planning metadata validation
"${linter_src}" "\$@"
LINTER_EXIT=\$?

if [ \$LINTER_EXIT -ne 0 ]; then
    echo "[TRACEABILITY GATE] Planning metadata validation failed. Commit aborted."
    exit \$LINTER_EXIT
fi

# 2. Delegate to standard/legacy pre-commit runner if present
if [ -x "${legacy_hook}" ]; then
    echo "[TRACEABILITY GATE] Planning validation passed. Delegating to standard pre-commit hooks..."
    "${legacy_hook}" "\$@"
    exit \$?
fi

exit 0
EOF
            chmod +x "$hook_dest"
            deployed=$((deployed + 1))
        fi
    done

    log_success "Pre-commit hooks deployed: ${deployed} wrapper(s) installed, ${skipped} skipped, ${failed} failed."
    return "$failed"
}

setup_workspace_from_yaml() {
    local ws_name="$1"
    local yaml_file="${SCRIPT_DIR}/workspace/workspaces.yaml"
    local ws_root="${HOME}/gft_studio/${ws_name}_workspace"
    local deps_dir="${ws_root}/dependencies"

    log_info "Setting up workspace '${ws_name}' from ${yaml_file}..."

    if [[ ! -f "$yaml_file" ]]; then
        log_error "workspaces.yaml not found at ${yaml_file}."
        return 1
    fi

    local ws_exists
    ws_exists=$(yq e ".workspaces | has(\"${ws_name}\")" "$yaml_file")
    if [[ "$ws_exists" != "true" ]]; then
        log_error "Workspace '${ws_name}' not defined in ${yaml_file}."
        return 1
    fi

    mkdir -p "$ws_root"
    mkdir -p "$deps_dir"

    local rw_repos
    rw_repos=$(yq e ".workspaces.${ws_name}.repos[].name" "$yaml_file" 2>/dev/null || true)
    
    for repo in $rw_repos; do
        if [[ -n "$repo" && "$repo" != "null" ]]; then
            log_info "Cloning R/W repo: ${repo}"
            if [[ ! -d "${ws_root}/${repo}" ]]; then
                git clone "https://github.com/GenCr-ft/${repo}.git" "${ws_root}/${repo}"
            else
                log_info "Repo ${repo} already exists, skipping."
            fi
        fi
    done

    local num_deps
    num_deps=$(yq e ".workspaces.${ws_name}.dependencies | length" "$yaml_file" 2>/dev/null || echo 0)
    
    local i=0
    while [[ $i -lt $num_deps ]]; do
        local dep_name
        local dep_tag
        dep_name=$(yq e ".workspaces.${ws_name}.dependencies[${i}].name" "$yaml_file")
        dep_tag=$(yq e ".workspaces.${ws_name}.dependencies[${i}].default_tag" "$yaml_file")
        
        if [[ -n "$dep_name" && "$dep_name" != "null" ]]; then
            log_info "Cloning dependency repo: ${dep_name} (Tag: ${dep_tag})"
            if [[ ! -d "${deps_dir}/${dep_name}" ]]; then
                git clone --branch "${dep_tag}" --depth 1 "https://github.com/GenCr-ft/${dep_name}.git" "${deps_dir}/${dep_name}"
                chmod -R 444 "${deps_dir}/${dep_name}"
                find "${deps_dir}/${dep_name}" -type d -exec chmod 555 {} +
            else
                log_info "Dependency ${dep_name} already exists, skipping."
            fi
        fi
        i=$((i + 1))
    done

    local vscode_ws_file="${HOME}/gft_studio/${ws_name}.code-workspace"
    log_info "Generating VS Code workspace file at ${vscode_ws_file}..."

    cat <<EOF > "$vscode_ws_file"
{
  "folders": [
EOF
    
    local is_first=true
    for repo in $rw_repos; do
        if [[ -n "$repo" && "$repo" != "null" ]]; then
            if [[ "$is_first" == "true" ]]; then
                is_first=false
            else
                echo "," >> "$vscode_ws_file"
            fi
            echo "    { \"name\": \"R/W: ${repo}\", \"path\": \"./${ws_name}_workspace/${repo}\" }" >> "$vscode_ws_file"
        fi
    done

    i=0
    while [[ $i -lt $num_deps ]]; do
        local dep_name
        dep_name=$(yq e ".workspaces.${ws_name}.dependencies[${i}].name" "$yaml_file")
        if [[ -n "$dep_name" && "$dep_name" != "null" ]]; then
            if [[ "$is_first" == "true" ]]; then
                is_first=false
            else
                echo "," >> "$vscode_ws_file"
            fi
            echo "    { \"name\": \"R/O: ${dep_name}\", \"path\": \"./${ws_name}_workspace/dependencies/${dep_name}\" }" >> "$vscode_ws_file"
        fi
        i=$((i + 1))
    done

    cat <<EOF >> "$vscode_ws_file"
  ],
  "settings": {
    "files.readonlyInclude": {
      "**/dependencies/**": true
    },
    "search.exclude": {
      "**/node_modules": true,
      "**/target": true,
      "**/pkg": true
    }
  }
}
EOF

    log_success "Workspace '${ws_name}' setup complete."
}
