#!/usr/bin/env bash
#
# ID: GFT_ONBOARDING_WORKSPACE_FILES_06
# Title: Onboarding Script - Workspace-Level File Deployment
# Author(s): AI Enablement Lead
# Creation Date: 2026-05-11
# Version: 1.0.0
#
# Description:
#   Deploys versioned workspace-level scripts and docs from the workspace/
#   bundle in this repo to $GFT_PROJECTS_HOME (default: ~/gft_studio).
#   Idempotent: skips files that are already up to date; updates changed ones.

deploy_workspace_files() {
    local target="${GFT_PROJECTS_HOME:-${HOME}/gft_studio}"
    local source_dir="${SCRIPT_DIR}/workspace"

    log_info "Deploying workspace-level files to ${target}..."

    if [[ ! -d "$source_dir" ]]; then
        log_error "Workspace bundle not found at ${source_dir}."
        return 1
    fi

    mkdir -p "$target"

    local deployed=0 updated=0 skipped=0

    while IFS= read -r -d '' src_file; do
        local filename
        filename="$(basename "$src_file")"
        local dest_file="${target}/${filename}"

        if [[ -f "$dest_file" ]] && diff -q "$src_file" "$dest_file" >/dev/null 2>&1; then
            log_info "  ${filename} — up to date."
            skipped=$((skipped + 1))
            continue
        fi

        if [[ -f "$dest_file" ]]; then
            log_info "  ${filename} — updating."
            updated=$((updated + 1))
        else
            log_info "  ${filename} — installing."
            deployed=$((deployed + 1))
        fi

        cp "$src_file" "$dest_file"
        if [[ "$src_file" == *.sh ]]; then
            chmod +x "$dest_file"
        fi
    done < <(find "$source_dir" -maxdepth 1 -type f -print0 | sort -z)

    log_success "Workspace files: ${deployed} installed, ${updated} updated, ${skipped} up to date."
}

deploy_planning_metadata_hook() {
    local target_dir="${GFT_PROJECTS_HOME:-${HOME}/gft_studio}"
    log_info "Deploying central planning metadata pre-commit hook..."

    # Canonical linter script path (resolved relative to the side-by-side repo layout)
    local linter_src="${target_dir}/gcd-ops-scripts/src/gft_ops_scripts/linters/validate_planning_metadata.py"

    # In a testing/mock environment, locate under target_dir as well
    if [[ ! -f "$linter_src" && -d "${target_dir}/linters" ]]; then
        linter_src="${target_dir}/linters/validate_planning_metadata.py"
    fi

    if [[ ! -f "$linter_src" ]]; then
        log_warn "Planning linter script not found at ${linter_src}. Skipping symlink hook deployment."
        return 0
    fi

    # Ensure the script is executable
    chmod +x "$linter_src"

    local deployed=0 skipped=0 failed=0

    # Scan all directories in target_dir to find Git repositories
    for repo_path in "${target_dir}"/*; do
        if [[ -d "${repo_path}/.git" ]]; then
            local repo_name
            repo_name=$(basename "$repo_path")
            local hook_dir="${repo_path}/.git/hooks"
            local hook_dest="${hook_dir}/pre-commit"
            local legacy_hook="${hook_dir}/pre-commit.legacy"

            mkdir -p "$hook_dir"

            # Check if this hook dest is already our wrapper and no legacy hook exists
            if [[ -f "$hook_dest" ]]; then
                if grep -q "GenCr@ft Studio - Chained Pre-Commit Hook wrapper" "$hook_dest" 2>/dev/null; then
                    if [[ ! -f "$legacy_hook" ]]; then
                        skipped=$((skipped + 1))
                        continue
                    fi
                fi
            fi

            # Handle existing hooks to enable chaining
            if [[ -f "$hook_dest" && ! -L "$hook_dest" ]]; then
                # If it's already a wrapper, don't move it to legacy!
                if ! grep -q "GenCr@ft Studio - Chained Pre-Commit Hook wrapper" "$hook_dest" 2>/dev/null; then
                    mv "$hook_dest" "$legacy_hook"
                    log_info "  Chained existing pre-commit hook in ${repo_name} to pre-commit.legacy"
                fi
            fi

            # Create the chained wrapper
            cat << EOF > "$hook_dest"
#!/usr/bin/env bash
# GenCr@ft Studio - Chained Pre-Commit Hook wrapper
# Automatically generated by onboarding scripts.

# 1. Run strict planning metadata validation
"${linter_src}" "\$@"
LINTER_EXIT=\$?

if [ \$LINTER_EXIT -ne 0 ]; then
    echo "[TRACEABILITY GATE] Planning metadata validation failed. Commit aborted."
    exit \$LINTER_EXIT
fi

# 2. Delegate to standard/legacy pre-commit runner if present
if [ -x "${legacy_hook}" ]; then
    echo "[TRACEABILITY GATE] Planning validation passed. Delegating to standard pre-commit hooks..."
    "${legacy_hook}" "\$@"
    exit \$?
fi

exit 0
EOF
            chmod +x "$hook_dest"
            deployed=$((deployed + 1))
        fi
    done

    log_success "Pre-commit hooks deployed: ${deployed} wrapper(s) installed, ${skipped} skipped, ${failed} failed."
    return "$failed"
}

